// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Playground.PaymentEngine.Store.EF.Accounts;

#nullable disable

namespace Playground.PaymentEngine.Store.EF.Migrations
{
    [DbContext(typeof(EFAccountStore))]
    partial class EFAccountStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Playground.PaymentEngine.Store.Accounts.Model.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Exposure")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPreferredAccount")
                        .HasColumnType("boolean");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("Account", "accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountTypeId = 1L,
                            CustomerId = 2L,
                            Exposure = 30.0m,
                            IsPreferredAccount = true,
                            TenantId = 1L
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Accounts.Model.AccountType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Charge")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ProcessOrder")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("AccountType", "accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Charge = 0m,
                            Name = "Visa",
                            ProcessOrder = 0,
                            TenantId = 1L,
                            Threshold = 0m
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("MetaData", "accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 1L,
                            Name = "AccountHolder",
                            TenantId = 1L,
                            Value = "Kate"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Accounts.Model.Account", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.Accounts.Model.AccountType", null)
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.Accounts.Model.Account", null)
                        .WithMany("MetaData")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Accounts.Model.Account", b =>
                {
                    b.Navigation("MetaData");
                });
#pragma warning restore 612, 618
        }
    }
}
