// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Playground.PaymentEngine.Store.EF.Terminals;

#nullable disable

namespace Playground.PaymentEngine.Store.EF.Migrations
{
    [DbContext(typeof(EFTerminalStore))]
    partial class EFTerminalStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TerminalResultId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TerminalResultId");

                    b.ToTable("MetaData", "terminals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "account-holder",
                            TenantId = 1L,
                            TerminalResultId = 1L,
                            Value = "E.L. Mare"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "card-number",
                            TenantId = 1L,
                            TerminalResultId = 1L,
                            Value = "123556456"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "cvc",
                            TenantId = 1L,
                            TerminalResultId = 1L,
                            Value = "547"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TerminalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("Setting", "terminals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "header:auth-user",
                            TenantId = 1L,
                            TerminalId = 1L,
                            Value = "Ettiene Mare"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "file_path",
                            TenantId = 1L,
                            TerminalId = 4L,
                            Value = "Exports"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Terminals.Model.Terminal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Terminal", "terminals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Rebilly",
                            RetryCount = 2,
                            TenantId = 1L,
                            Type = "http"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CustomTerminal",
                            RetryCount = 2,
                            TenantId = 1L,
                            Type = "http"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "GlobalPay",
                            RetryCount = 2,
                            TenantId = 1L,
                            Type = "http"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Rebilly_File",
                            RetryCount = 1,
                            TenantId = 1L,
                            Type = "stream"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Orca",
                            RetryCount = 1,
                            TenantId = 1L,
                            Type = "http"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Terminals.Model.TerminalMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("TerminalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TerminalMap", "terminals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountTypeId = 88L,
                            Enabled = true,
                            Order = (short)0,
                            TenantId = 1L,
                            TerminalId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AccountTypeId = 98L,
                            Enabled = true,
                            Order = (short)0,
                            TenantId = 1L,
                            TerminalId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            AccountTypeId = 88L,
                            Enabled = true,
                            Order = (short)1,
                            TenantId = 1L,
                            TerminalId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            AccountTypeId = 90L,
                            Enabled = true,
                            Order = (short)1,
                            TenantId = 1L,
                            TerminalId = 4L
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Terminals.Model.TerminalResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Terminal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TerminalResult", "terminals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "00",
                            Date = new DateTime(2000, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Test Message",
                            Reference = "44543434",
                            Success = false,
                            TenantId = 1L,
                            Terminal = "Rebilly"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.Terminals.Model.TerminalResult", null)
                        .WithMany("MetaData")
                        .HasForeignKey("TerminalResultId");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.Setting", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.Terminals.Model.Terminal", null)
                        .WithMany("Settings")
                        .HasForeignKey("TerminalId");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Terminals.Model.Terminal", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Terminals.Model.TerminalResult", b =>
                {
                    b.Navigation("MetaData");
                });
#pragma warning restore 612, 618
        }
    }
}
