global using System.IO;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.Hosting;
global using Microsoft.OpenApi.Models;
global using Playground.Core.Events;
global using Playground.PaymentEngine.Events;
global using Playground.PaymentEngine.Helpers;
global using Playground.PaymentEngine.Services.CacheService;
global using Playground.PaymentEngine.Services.Routing;
global using Playground.PaymentEngine.Stores.Accounts;
using Playground.PaymentEngine.Stores.Accounts.File;
using Playground.PaymentEngine.Stores.Allocations;
using Playground.PaymentEngine.Stores.Allocations.File;
using Playground.PaymentEngine.Stores.ApprovalRules;
using Playground.PaymentEngine.Stores.ApprovalRules.File;
using Playground.PaymentEngine.Stores.Customers;
using Playground.PaymentEngine.Stores.Customers.File;
using Playground.PaymentEngine.Stores.Terminals;
using Playground.PaymentEngine.Stores.Terminals.File;
using Playground.PaymentEngine.Stores.Withdrawals;
using Playground.PaymentEngine.Stores.Withdrawals.File;
using Playground.PaymentEngine.Terminals.Functions;
using Playground.PaymentEngine.UseCases.Payments.AutoAllocate;
using Playground.PaymentEngine.UseCases.Payments.Callback;
using Playground.PaymentEngine.UseCases.Payments.Process;
using Playground.PaymentEngine.UseCases.Payments.RunApprovalRules;
using Playground.Router;
using Playground.Router.Clients;
using Playground.Router.Clients.File;
using Playground.Rules;
using Playground.Rules.CustomActions.Terminal;