### Get a list of all the allocations
GET {{baseUrl}}/allocations
Content-Type: application/json

>> responses/allocations.json

### Get request 190
GET {{baseUrl}}/allocations/190
Content-Type: application/json

>> responses/allocations_190.json

### Create Allocations
POST {{baseUrl}}/allocations
Content-Type: application/json

{
  "withdrawalGroupId": 1,
  "accountId": 267,
  "amount": 13.00,
  "charge": 0.00
}

>> responses/allocations_new.json

### Delete Allocation 189
DELETE {{baseUrl}}/allocations/189
Content-Type: application/json

>> responses/allocations_delete.json

### Auto Allocate
POST {{baseUrl}}/allocations/auto-allocate
Content-Type: application/json

{
  "withdrawalGroups": [ 1, 2 ]
}

>> responses/allocations_auto_allocate.json