// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Playground.PaymentEngine.Store.EF.ApprovalRules;

#nullable disable

namespace Playground.PaymentEngine.Store.EF.Migrations
{
    [DbContext(typeof(EFApprovalRuleStore))]
    partial class EFApprovalRuleStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Playground.PaymentEngine.Store.ApprovalRules.Model.ApprovalRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalRuleHistoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRuleHistoryId");

                    b.ToTable("ApprovalRule", "approval_rules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApprovalRuleHistoryId = 1L,
                            IsSuccessful = true,
                            Message = "Rule 1 succeeded",
                            RuleName = "rule1",
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ApprovalRuleHistoryId = 1L,
                            IsSuccessful = true,
                            Message = "Rule 2 succeeded",
                            RuleName = "rule2",
                            TenantId = 1L
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.ApprovalRules.Model.ApprovalRuleHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<long>("WithdrawalGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ApprovalRuleHistory", "approval_rules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            TenantId = 1L,
                            TransactionDate = new DateTime(2020, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = new Guid("8c5c1ae6-b2ab-4715-aebe-258a64aee52d"),
                            WithdrawalGroupId = 2L
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovalRuleHistoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRuleHistoryId");

                    b.ToTable("MetaData", "approval_rules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApprovalRuleHistoryId = 1L,
                            Name = "withdrawal-id",
                            TenantId = 1L,
                            Value = "1"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.ApprovalRules.Model.ApprovalRule", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.ApprovalRules.Model.ApprovalRuleHistory", null)
                        .WithMany("Rules")
                        .HasForeignKey("ApprovalRuleHistoryId");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.ApprovalRules.Model.ApprovalRuleHistory", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ApprovalRuleHistoryId");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.ApprovalRules.Model.ApprovalRuleHistory", b =>
                {
                    b.Navigation("Metadata");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
