// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Playground.PaymentEngine.Store.EF.Customers;

#nullable disable

namespace Playground.PaymentEngine.Store.EF.Migrations.EFCustomerStoreMigrations
{
    [DbContext(typeof(EFCustomerStore))]
    [Migration("20211128045755_customer_setup")]
    partial class CustomerSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Playground.PaymentEngine.Store.Customers.Model.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Customer", "customers");

                    b.HasData(
                        new
                        {
                            Id = 44L,
                            Balance = 3400.0m,
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 74L,
                            Balance = 1.0m,
                            TenantId = 1L
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MetaData", "customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CustomerId = 44L,
                            Name = "firstName",
                            TenantId = 1L,
                            Value = "Ettiene"
                        },
                        new
                        {
                            Id = 2L,
                            CustomerId = 44L,
                            Name = "lastName",
                            TenantId = 1L,
                            Value = "Mare"
                        },
                        new
                        {
                            Id = 3L,
                            CustomerId = 44L,
                            Name = "hasKYC",
                            TenantId = 1L,
                            Value = "true"
                        },
                        new
                        {
                            Id = 4L,
                            CustomerId = 74L,
                            Name = "firstName",
                            TenantId = 1L,
                            Value = "Kate"
                        },
                        new
                        {
                            Id = 5L,
                            CustomerId = 74L,
                            Name = "lastName",
                            TenantId = 1L,
                            Value = "Moss"
                        });
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Model.MetaData", b =>
                {
                    b.HasOne("Playground.PaymentEngine.Store.Customers.Model.Customer", null)
                        .WithMany("MetaData")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Playground.PaymentEngine.Store.Customers.Model.Customer", b =>
                {
                    b.Navigation("MetaData");
                });
#pragma warning restore 612, 618
        }
    }
}
